# Generated by Django 6.0.5 on 2026-05-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('angry', '😠 Angry')], default='happy', max_length=10),
        ),
    ]
