# Generated by Django 6.0.5 on 2026-05-21 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '🚫 Spam'), ('harassment', '😡 Harassment'), ('hate', '💢 Hate Speech'), ('false', '❌ False Information'), ('other', '📝 Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wall.confession')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('confession', 'reporter')},
            },
        ),
    ]
