# Generated by Django 6.0.5 on 2026-05-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='wall.userprofile'),
        ),
    ]
