# Generated by Django 6.0.5 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='confessions/'),
        ),
    ]
