# Generated by Django 6.0.5 on 2026-05-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0012_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
