# Generated by Django 6.0.5 on 2026-05-31 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0013_confession_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
