# Generated by Django 6.0.5 on 2026-06-10 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0014_alter_confession_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('❤️', '❤️ Love'), ('😂', '😂 Haha'), ('😮', '😮 Wow'), ('😢', '😢 Sad'), ('😡', '😡 Angry')], max_length=10)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='wall.confession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('confession', 'user', 'emoji')},
            },
        ),
    ]
